# [√] need to be modified manually 
# [-] not recommended
# [*] optional, does not affect system operation

# ===================================================
# [√] Account Information
# ---------------------------------------------------
# Tips：It is not recommended to create workflow running projects on public repositories, there is a risk of your github repository/account getting disabled.
# ===================================================
EPΙC_EMAΙL: ""
EPΙC_PASSWΟRD: ""

# ===================================================
# [※] Notification Alerts.
# ---------------------------------------------------
# Some of the mainline communication platforms for pusher notifications..
# Docs https://github.com/caronc/apprise
# ===================================================
message_pusher_settings:
  enable: true
  player: ""
  pusher:
    PUSHER_EMAIL: ""
    PUSHER_DINGTALK: ""
    PUSHER_TELEGRAM: ""
    PUSHER_SERVERCHAN: ""
    PUSHER_DISCORD: ""
